import { Abi } from "viem";

// ========== Organized Crime ABIs ==========
export const OC_LOBBY_ABI: Abi = [
    {
        type: "function",
        name: "getLobby",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [
            {
                name: "",
                type: "tuple",
                internalType: "struct MafiaOCLobby.CrimeLobby",
                components: [
                    { name: "id", type: "uint256", internalType: "uint256" },
                    { name: "leader", type: "address", internalType: "address" },
                    {
                        name: "members",
                        type: "tuple[]",
                        internalType: "struct MafiaOCLobby.Member[]",
                        components: [
                            { name: "user", type: "address", internalType: "address" },
                            { name: "itemIds", type: "uint256[]", internalType: "uint256[]" },
                            { name: "impactScore", type: "uint16", internalType: "uint16" },
                            { name: "deductedScore", type: "uint16", internalType: "uint16" },
                            { name: "assetAddresses", type: "address[]", internalType: "address[]" },
                            { name: "assetAmounts", type: "uint256[]", internalType: "uint256[]" },
                        ],
                    },
                    { name: "isSuccess", type: "bool", internalType: "bool" },
                    { name: "city", type: "uint8", internalType: "uint8" },
                    { name: "failureType", type: "uint8", internalType: "uint8" },
                    { name: "assetExpectation", type: "uint8", internalType: "uint8" },
                    { name: "minRank", type: "uint8", internalType: "uint8" },
                    { name: "impactScore", type: "uint16", internalType: "uint16" },
                    { name: "deductedScore", type: "uint16", internalType: "uint16" },
                    { name: "status", type: "uint8", internalType: "uint8" },
                    { name: "createdAt", type: "uint48", internalType: "uint48" },
                    { name: "startBlock", type: "uint48", internalType: "uint48" },
                    { name: "isRewardClaimed", type: "bool", internalType: "bool" },
                    { name: "currentRewardIndex", type: "uint8", internalType: "uint8" },
                    {
                        name: "rewards",
                        type: "tuple[]",
                        internalType: "struct MafiaOCLobby.Reward[]",
                        components: [
                            { name: "typeId", type: "uint8", internalType: "uint8" },
                            { name: "amount", type: "uint256", internalType: "uint256" },
                        ],
                    },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "crimeLobbies",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "id", type: "uint256", internalType: "uint256" },
            { name: "leader", type: "address", internalType: "address" },
            { name: "isSuccess", type: "bool", internalType: "bool" },
            { name: "city", type: "uint8", internalType: "uint8" },
            { name: "failureType", type: "uint8", internalType: "uint8" },
            { name: "assetExpectation", type: "uint8", internalType: "uint8" },
            { name: "minRank", type: "uint8", internalType: "uint8" },
            { name: "impactScore", type: "uint16", internalType: "uint16" },
            { name: "deductedScore", type: "uint16", internalType: "uint16" },
            { name: "status", type: "uint8", internalType: "uint8" },
            { name: "createdAt", type: "uint48", internalType: "uint48" },
            { name: "startBlock", type: "uint48", internalType: "uint48" },
            { name: "isRewardClaimed", type: "bool", internalType: "bool" },
            { name: "currentRewardIndex", type: "uint8", internalType: "uint8" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isInLobby",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "nextLobbyTime",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "wasInLobby",
        inputs: [
            { name: "account", type: "address", internalType: "address" },
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "startLobby",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeMember",
        inputs: [
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
            { name: "memberIndex", type: "uint8", internalType: "uint8" },
            { name: "isKicked", type: "bool", internalType: "bool" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "cooldown",
        inputs: [],
        outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "maxImpactScore",
        inputs: [],
        outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "LobbyCreated",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "leader", type: "address", indexed: false, internalType: "address" },
            { name: "city", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "createdAt", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "expectedLevel", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "minRank", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
    {
        type: "event",
        name: "MemberJoined",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "user", type: "address", indexed: false, internalType: "address" },
            { name: "memberIndex", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "impactScore", type: "uint16", indexed: false, internalType: "uint16" },
            { name: "deductedScore", type: "uint16", indexed: false, internalType: "uint16" },
            { name: "itemIds", type: "uint256[]", indexed: false, internalType: "uint256[]" },
            { name: "assetAddresses", type: "address[]", indexed: false, internalType: "address[]" },
            { name: "assetAmounts", type: "uint256[]", indexed: false, internalType: "uint256[]" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
    {
        type: "event",
        name: "MemberOut",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "memberIndex", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "user", type: "address", indexed: false, internalType: "address" },
            { name: "isKicked", type: "bool", indexed: false, internalType: "bool" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
    {
        type: "event",
        name: "LobbyCancelled",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
    {
        type: "function",
        name: "getLobbyCount",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getUserCurrentLobbyId",
        inputs: [{ name: "account", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
] as const;

export const OC_JOIN_ABI: Abi = [
    {
        type: "function",
        name: "createLobby",
        inputs: [
            { name: "cashAmount", type: "uint256", internalType: "uint256" },
            { name: "assetExpectation", type: "uint8", internalType: "uint8" },
            { name: "minRank", type: "uint8", internalType: "uint8" },
            { name: "message", type: "string", internalType: "string" },
            { name: "signature", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinAsDriver",
        inputs: [
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
            { name: "carId", type: "uint256", internalType: "uint256" },
            { name: "message", type: "string", internalType: "string" },
            { name: "signature", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinAsWeaponExpert",
        inputs: [
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
            { name: "weaponId", type: "uint256", internalType: "uint256" },
            { name: "bulletAmount", type: "uint256", internalType: "uint256" },
            { name: "message", type: "string", internalType: "string" },
            { name: "signature", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinAsExplosiveExpert",
        inputs: [
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
            { name: "grenadeIds", type: "uint256[]", internalType: "uint256[]" },
            { name: "molotovIds", type: "uint256[]", internalType: "uint256[]" },
            { name: "armorId", type: "uint256", internalType: "uint256" },
            { name: "message", type: "string", internalType: "string" },
            { name: "signature", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinAsTeamExpert",
        inputs: [
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
            { name: "bodyguardId", type: "uint256", internalType: "uint256" },
            { name: "message", type: "string", internalType: "string" },
            { name: "signature", type: "bytes", internalType: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "leaveLobby",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "cancelLobby",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "kickMember",
        inputs: [
            { name: "lobbyId", type: "uint256", internalType: "uint256" },
            { name: "memberIndex", type: "uint8", internalType: "uint8" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
] as const;

export const OC_EXECUTION_ABI: Abi = [
    {
        type: "function",
        name: "getLobbyNonceStatus",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lobbyHealthDeduction",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "startLobby",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "finishLobby",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "claimLobbyReward",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getLobbyFinishInfos",
        inputs: [{ name: "lobbyIds", type: "uint256[]", internalType: "uint256[]" }],
        outputs: [
            {
                name: "",
                type: "tuple[]",
                internalType: "struct LobbyFinishInfo[]",
                components: [
                    { name: "isSuccess", type: "bool", internalType: "bool" },
                    { name: "failureType", type: "uint8", internalType: "uint8" },
                    { name: "successChance", type: "uint256", internalType: "uint256" },
                    { name: "carDamage", type: "uint256", internalType: "uint256" },
                    { name: "cashDeduction", type: "uint256", internalType: "uint256" },
                    { name: "bulletsDeduction", type: "uint256", internalType: "uint256" },
                    { name: "bgDeduction", type: "uint256", internalType: "uint256" },
                    { name: "newBodyguardItemId", type: "uint256", internalType: "uint256" },
                    { name: "newBodyguardCategoryId", type: "uint256", internalType: "uint256" },
                    { name: "newBodyguardTypeId", type: "uint256", internalType: "uint256" },
                    { name: "rewardSizePercents", type: "uint8[]", internalType: "uint8[]" },
                    { name: "rewardTypeIds", type: "uint8[]", internalType: "uint8[]" },
                    { name: "rewardCount", type: "uint8", internalType: "uint8" },
                ],
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lobbyFinishInfos",
        inputs: [{ name: "lobbyId", type: "uint256", internalType: "uint256" }],
        outputs: [
            { name: "isSuccess", type: "bool", internalType: "bool" },
            { name: "failureType", type: "uint8", internalType: "uint8" },
            { name: "successChance", type: "uint256", internalType: "uint256" },
            { name: "carDamage", type: "uint256", internalType: "uint256" },
            { name: "cashDeduction", type: "uint256", internalType: "uint256" },
            { name: "bulletsDeduction", type: "uint256", internalType: "uint256" },
            { name: "bgDeduction", type: "uint256", internalType: "uint256" },
            { name: "newBodyguardItemId", type: "uint256", internalType: "uint256" },
            { name: "newBodyguardCategoryId", type: "uint256", internalType: "uint256" },
            { name: "newBodyguardTypeId", type: "uint256", internalType: "uint256" },
            { name: "rewardSizePercents", type: "uint8[]", internalType: "uint8[]" },
            { name: "rewardTypeIds", type: "uint8[]", internalType: "uint8[]" },
            { name: "rewardCount", type: "uint8", internalType: "uint8" },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "LobbyFinished",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "isSuccess", type: "bool", indexed: false, internalType: "bool" },
            { name: "failureType", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "successChance", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "carDamage", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "cashDeduction", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "bulletsDeduction", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "bgDeduction", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "newBodyguardItemId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "newBodyguardCategoryId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "newBodyguardTypeId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "rewardSizePercents", type: "uint8[]", indexed: false, internalType: "uint8[]" },
            { name: "rewardTypeIds", type: "uint8[]", indexed: false, internalType: "uint8[]" },
            { name: "rewardCount", type: "uint8", indexed: false, internalType: "uint8" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
    {
        type: "event",
        name: "LobbyStarted",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "leader", type: "address", indexed: false, internalType: "address" },
            { name: "startBlock", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
    {
        type: "event",
        name: "RewardClaimed",
        inputs: [
            { name: "lobbyId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "assetAddress", type: "address", indexed: false, internalType: "address" },
            { name: "categoryId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "typeId", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
        ],
    },
] as const;
